### ISSUE TITLE
Not able to replicate results for HalfCheetah-v1

### ISSUE THREAD

**Issue by a7b23** [maximecb/baby-ai-game#1]
Did you use the same set of hyperparameters for Reacher-v1 and HalfCheetah-v1?
I am getting the desired result for Reacher-v1 experiment

**Comment by maximecb** [comment]
You're referring to the code under `basicrl`? I'm not the author, it's a modified copy of this repository:
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr

I put the code in there to get people started with our gym environment. Had to modify it to support our environment properly.
