### ISSUE TITLE
Levels & Lessons

### ISSUE THREAD

**Issue by maximecb** [maximecb/baby-ai-game#18]
For both the levels and our curriculum of lessons, we will need to constrain the generation of instructions. We need the instruction generation code, and probably the environment generation, to accept a set of parameters.

Some things we might want to limit:
- limit the length of instruction sequences generated
- only allowing specific actions to be in the instructions
- limiting objects referenced to all be in the same room as the agent

Some possible example levels:
- level 0: go to the red door (which in the current room)
- level 1: go to door or pick up object of any color (in the current room)
- level 2: pick up an object (in the current room)
- level 3: pick up a key (in the current room) and unlock a door
- level 4: go through a door and pick an object (object is in the next room)

**Comment by lcswillems** [comment]
Maybe a way to create lessons is to:

1. Determine skills the agent may acquire.
2. Determine parameters we can play on to complexify missions.
3. Determine lessons involving these skills with increasing complexity.

# 1. Skills

Elementary skills:

1. execute an action (`pick up`, `drop`, `go to`, `open` something)
2. execute a sequence of actions
3. distinguish objects type (`door`, `key`, `box`, `goal`)
4. distinguish colors (`blue`, `red`, ...)
5. geolocate in the map (`north`, `east`, ...)
6. move blocking objects
7. remember past positions
8. remember past crucial positions

# 2. Parameters

1. adding disturbing objects
2. adding disturbing rooms
3. increasing rooms size
4. increasing "distance" between objects and baby (e.g. "distance" can be seen as number of doors to open)
5. adding disturbing instructions
6. hiding objects in boxes

# 3. Lessons

Course called `pick up key` with 9 lessons:

A.1. `pick up COLOR? key`, 1 room, 1 key
A.2. `pick up COLOR? key`, 1 room, 1 box with 1 key
A.3. `pick up COLOR? key`, 2 rooms, 1 key in the current room
A.4. `pick up COLOR? key`, 2 rooms, 1 key in the 2nd room
A.5. `pick up COLOR? key`, 2 rooms, 1 box with 1 key in the 2nd room
A.6. `pick up COLOR? key`, 1 room, 1 key, 1 non-key pickup-able object
A.7. `pick up COLOR? key`, 1 room, 2 keys
A.9. `pick up COLOR? key at POS`, 3x3 rooms, 1 key

**Comment by maximecb** [comment]
For now, the levels are defined in:
https://github.com/maximecb/baby-ai-game/blob/master/levels/levels.py

Each level is usable as a Gym environment. Missions can be samples randomly automatically, each time the environment is reset. It's possible to sample the same mission multiple times by calling `env.seed(my_mission_seed_value)` before calling reset.

I will close this issue for the time being, because I feel like having a zillion open issues makes it hard to determine which problems are actually blocking or in need of solutions.
