### ISSUE TITLE
plug-and-play conda environment 

### ISSUE THREAD

**Issue by rizar** [maximecb/baby-ai-game#9]
It would be good to provide a plug-and-play conda environment with this repository that people can build and have everything up and running.

**Comment by maximecb** [comment]
How do you go about packaging a conda environment? Put everything in a conda package?

**Comment by dmitriy-serdyuk** [comment]
@rizar , is there need for conda env when the project doesn't have any C/C++ dependencies? I didn't have any problems installing everything with pip (under conda).

What are the advantages?

**Comment by maximecb** [comment]
I did make an effort to minimize the number of dependencies. It should just be a matter of installing pytorch, and then installing the other dependencies with pip3.

**Comment by dmitriy-serdyuk** [comment]
Installing PyQT is a bit simpler with conda.

So, it would be an env with PyQT, gym, and pytorch preinstalled?

**Comment by maximecb** [comment]
Pytorch, 

'gym>=0.9.6',
'numpy>=1.10.0',
'pyqt5>=5.10.1'

And also visdom.

**Comment by rizar** [comment]
And I also had to install matplotlib in order to train the agent. 

Wouldn't it be great if a new person could start working with the project just by doing `conda env create -f environment.yml`?

Also, think about running this code at a cluster, in the cloud, etc. Installing dependencies every time is not the 21st century :)

**Comment by maximecb** [comment]
I believe I eliminated the dependency on matplotlib a few days ago, but either way.

I have no objections, but I don't really use conda, so I'm not familiar with it. @rizar, could you make a PR for an environment.yml and update the README under usage at MILA? You know best what it is that you want.

**Comment by rizar** [comment]
okey-dockey, will look into it :)
